// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBK9OB8cSNZg99QRr_IUubHOWTMnWQADE',
    appId: '1:330833148559:android:08754d30189275a16bcefa',
    messagingSenderId: '330833148559',
    projectId: 'roque-advmobprog-firebase',
    storageBucket: 'roque-advmobprog-firebase.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPuGD4oP2_YTsYNPytnHzBmvaCMDglRXM',
    appId: '1:330833148559:ios:c2e1a119eadb646b6bcefa',
    messagingSenderId: '330833148559',
    projectId: 'roque-advmobprog-firebase',
    storageBucket: 'roque-advmobprog-firebase.firebasestorage.app',
    iosBundleId: 'com.example.roqueAdvmobprog',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQI22NQis-Wu9ULVDF9DTmr8T0JAKs7rk',
    appId: '1:330833148559:web:ff4879050310b1926bcefa',
    messagingSenderId: '330833148559',
    projectId: 'roque-advmobprog-firebase',
    authDomain: 'roque-advmobprog-firebase.firebaseapp.com',
    storageBucket: 'roque-advmobprog-firebase.firebasestorage.app',
    measurementId: 'G-363ET3943V',
  );
}
